- hosts: localhost
  tasks:
    - name: Gather server information 
      openstack.cloud.server_info:
        name: aa*
        filters:
          vm_state: active
      register: my_servers
    - name: debug
      debug:
        msg: "{{ my_servers }}"
    - name: Gather flaovr information 
      openstack.cloud.compute_flavor_info:
      register: my_flavors
    - name: debug
      debug:
        msg: "{{ my_flavors }}"
